version: 2
registries:
  powershell-gallery:
    type: nuget-feed
    url: https://www.powershellgallery.com/api/v2/
  nuget_org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
    timezone: America/LosAngeles
  open-pull-requests-limit: 10
  registries:
  - powershell-gallery
  - nuget-org
