variables:
  pwsh: true
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

stages:
  - stage: Build
    jobs:
      - job: 'Full_Build'
        pool:
          vmImage: windows-latest
        steps:
        - pwsh: |
            Import-Module .\tools\appveyor.psm1
            Invoke-AppveyorInstall -SkipPesterInstallation
            ./build.ps1 -Configuration 'Release' -All
            ./PSCompatibilityCollector/build.ps1 -Configuration 'Release' -Framework 'netstandard2.0'
          displayName: 'Full Build'
        - task: PublishPipelineArtifact@1
          displayName: 'Publish Pipeline Artifact: out Folder'
          inputs:
            targetPath: '$(Build.SourcesDirectory)/out'
            artifactName: out
  - stage: Test
    jobs:
      - job: Strategy
        strategy:
          matrix:
            ubuntu16:
              containerImage: ubuntu:16.04
            ubuntu18:
              containerImage: ubuntu:18.04
        pool:
          vmImage: $[ variables['containerImage'] ]
        steps:
        - template: templates/test.yaml
          parameters:
            pwsh: false
